# we will use node:alpine docker image
FROM node:alpine
FROM maven:3.6.3-jdk-8-slim
FROM php:5.6.30-fpm-alpine



# set /app as work directory
WORKDIR /app

# copy package.json to work directory, so that we install npm dependencies
COPY package.json /app

# install npm dependencies
RUN yarn

# copy your project files to work directory
COPY . /app

# run your app
CMD ["yarn", "dev"] 