version: "1"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "6000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
